# Generated by Django 4.1.1 on 2022-09-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flybookfly', '0002_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
