# Generated by Django 4.1.1 on 2022-09-13 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flybookfly', '0003_book_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Отправлено в архив'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(to='flybookfly.author', verbose_name='Автор книги'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flybookfly.author', verbose_name='Автор комментария')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flybookfly.book', verbose_name='Книга')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
