# Generated by Django 4.1.1 on 2022-09-15 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flybookfly', '0006_author_slug_alter_book_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='slug',
        ),
    ]
